### ISSUE TITLE
Please check and give your feedback!

### ISSUE THREAD

**Issue by FloorD** [rails-girls-summer-of-code/RGSoC_slides#1]
Thanks <3

**Comment by anikalindtner** [comment]
hej floor, where did you get the numbers for the teams and students? i guess it's 18 teams and 33 students and so on.. otherwise i think it's good! :)

do you already think of a design?

**Comment by FloorD** [comment]
Yup, but I need to install keynote again I guess! Will do so today :)
I'll change the numbers into 18 and 33, but what is 'so on'? More inconsistencies? 

Thanks

**Comment by anikalindtner** [comment]
hej, i just meant that we should check the numbers again.. but they are all good. except that we now are 10 supervisors. and we have tiffany, juliane, dirkjan, tim, patrick, chad, evan, (caroline (haven't heard back)) as speaker coaches, and i'm sure i'm forgetting someone.. so that's at least 8 speaker coaches :)

**Comment by anikalindtner** [comment]
when do you think you can have this ready? because i'm working on the konferenz-tips-article and this would be supercool if we can publish that together :)

**Comment by FloorD** [comment]
The general info is ready, I can do the slides tonight and have them ready
by tomorrow morning!
F

**Comment by anikalindtner** [comment]
awesome! just let me know, when they are ready - then i'll publish the blog post :)

**Comment by anikalindtner** [comment]
huhu,

thanks for editing the speaker coaches <3 

i just looked through the slides with sven and he said they are awesome! just for the sponsor part: we only need the first slide. all the other sponsors apparantly didn't get the promise from us to be mentioned and for a lightning talk one sponsor slide should be enough :)

**Comment by FloorD** [comment]
Ok, cool, I can throw them out or we can mention it in the talk.md, that
they can leave out these slides.
I was suddenly put on this project (DevFest Vienna hackathon organizing)
somehow, but as of tomorrow I finally have time  to finish my blogs on
conferences, Travis and Google Open Source.

All the best (also to Sven).

Floor

**Comment by anikalindtner** [comment]
hej floor! awesome :) i'd say we can just write it in the .md, because they look so nice. so we don't have to throw them out <3 

if you need help with anything else, ping me! 
oh and for the github blogpost, team species+ is preparing a thank-you message on video. maybe we could ping team inchworms for travis?

gooooood morning! (only one week until i'm in vienna again! whoop)

**Comment by FloorD** [comment]
hej floor! awesome :) i'd say we can just write it in the .md, because they
look so nice. so we don't have to throw them out <3

will do

if you need help with anything else, ping me!
oh and for the github blogpost, team species+ is preparing a thank-you
message on video. maybe we could ping team inchworms for travis?

and... will do!

F

**Comment by sakshi-keepworks** [comment]
Great work :+1:

**Comment by alicetragedy** [comment]
This issue has been dealt with and stuff (also it's like... 4 years old) so I'm gonna go ahead and close this. Thank you @FloorD for all your work on RGSoC ❤️
